import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React from 'react'

export default function Home() {
  const [selectedFile, setSelectedFile] = React.useState('')
  const [previewSrc, setPreviewSrc] = React.useState('')

  const handleFileInputChange = (e) => {
    console.log(e.target.files[0])
    const file = e.target.files[0]
    setSelectedFile(file)
    // transform file
    previewFile(file)
  }

  // Image Transformation to ArrayBuffer.
  const previewFile = file => {
    const reader = new FileReader()
    reader.readAsDataURL(file)
    reader.onloadend = () => {
      setPreviewSrc(reader.result)
      console.log("Image is now transformed! ", typeof reader.result)
      console.log("Image is now transformed! ", reader.result)
    }
    reader.onerror = () => alert("An error occurred while reading image file!")
  }

  // Submit for preview.
  const handleSubmitFile = async (e) => {
    e.preventDefault()
    if (!previewSrc) return alert("No file selected.")

    let product = {
      title: 'Test Product Image Title',
      image: previewSrc,
      brand: 'Brand Image tEST',
      price: 200,
      description: "Testing product Image upload to cloudinary.",
      countInStock: 10
    }

    const res = await fetch('/api/admin/create/product', {
      method: 'POST',
      body: JSON.stringify(product),
      headers: {
        "Content-Type": "application/json"
      }
    })

    const data = await res.json()
    console.log("Response From Creating Product with Image Saved to Cloudinary:>> ", data)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div>
          <h2 className="text-blue-600">Image Uplaod</h2>
          <form onSubmit={handleSubmitFile}>
            <input type="file" onChange={handleFileInputChange} />
            <button type="submit">Upload Image</button>
          </form>
          {previewSrc && (
            <Image src={previewSrc} width={200} height={200} />
          )}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
